classdef numericArray < matlab.mixin.indexing.RedefinesParen & matlab.mixin.indexing.RedefinesBrace
    properties (SetAccess=protected)
        Dimension   (1,:)   double  = [1,1]
        Data        
    end
    %% CONSTRUCTOR
    methods
        function obj = numericArray(varargin)
        end
    end
    %% PROTECTED METHODS
    methods (Access=protected)
        varargout = braceReference(obj,indexOp)
        obj = braceAssign(obj,indexOp,varargin)
        n = braceListLength(obj,indexOp,indexContext)
        varargout = parenReference(obj,indexOp)
        obj = parenAssign(obj,indexOp,varargin)
        n = parenListLength(obj,indexOp,indexContext)
        obj = parenDelete(obj,indexOp)
        obj = dimcat(dim,varargin)
    end
    %% PUBLIC METHODS
    methods (Access=public)
        varargout = size(obj,varargin)
        ind = end(obj,k,n)
        obj = cat(dim,varargin)
        B = permute(A,dimorder)
        B = transpose(A)
        B = ctranspose(A)
        B = reshape(A,varargin)
        TF = isfinite(A)
        TF = isinf(A)
        TF = isnan(A)
        TF = isreal(A)
        TF = isnumeric(A)
        TF = eq(A,B)
        TF = ne(A,B)
        TF = gt(A,B)
        TF = ge(A,B)
        TF = lt(A,B)
        TF = le(A,B)
        Y = floor(X)
        Y = ceil(X)
        Y = fix(X)
        Y = round(X)
        Y = abs(X)
        Y = sign(X)
        Zc = conj(Z)
        C = uplus(A)
        C = uminus(A)
        C = plus(A,B)
        C = minus(A,B)
        C = times(A,B)
        C = mtimes(A,B)
        C = rdivide(A,B)
        C = mrdivide(B,A)
        C = ldivide(B,A)
        C = mldivide(A,B)
        C = power(A,B)
        C = mpower(A,B)
        R = rem(A,B)
        B = mod(A,M)
        typename = underlyingType(obj)
        B = castUnderlyingType(A,varargin)
        B = cast(A,varargin)
        B = double(A)
        B = single(A)
        B = int8(A)
        B = int16(A)
        B = int32(A)
        B = int64(A)
        B = uint8(A)
        B = uint16(A)
        B = uint32(A)
        B = uint64(A)
    end
    %% STATIC METHODS
    methods (Static)
        obj = empty(classname,dimension,varargin)
        obj = createArray(dims,fillValue)
    end
    %% HIDDEN METHODS
    methods (Hidden)
        mustBePositive(A)
        mustBeNonpositive(A)
        mustBeNonnegative(A)
        mustBeNegative(A)
        mustBeFinite(A)
        mustBeNonNan(A)
        mustBeNonzero(A)
        mustBeReal(A)
        mustBeInteger(A)
    end
end